CREATE TABLE IF NOT EXISTS IDN_BASE_TABLE (
            PRODUCT_NAME VARCHAR (20),
            PRIMARY KEY (PRODUCT_NAME)
);

INSERT INTO IDN_BASE_TABLE values ('WSO2 Identity Server');


CREATE TABLE IF NOT EXISTS IDN_PROVISIONING_STATUS (
  STATUS_ID INTEGER NOT NULL AUTO_INCREMENT,
  TENANT_ID INTEGER,
  IDP_NAME VARCHAR(254),
  STATUS VARCHAR(10),
  ENTITY VARCHAR(10),
  ENTITY_NAME VARCHAR(60),
  CONNECTOR VARCHAR(30),
  OPERATION VARCHAR(10),
  CAUSE VARCHAR(512),
  PRIMARY KEY (STATUS_ID)
);

CREATE TABLE IF NOT EXISTS IDN_PROVISIONING_METADATA (
  METADATA_ID INTEGER NOT NULL AUTO_INCREMENT,
  STATUS_ID INTEGER NOT NULL,
  TENANT_ID INTEGER,
  PROVISIONING_ENTITY TEXT,
  CONNECTOR_CONFIG TEXT,
  PRIMARY KEY (METADATA_ID)
--   FOREIGN KEY (STATUS_ID) REFERENCES IDN_PROVISIONING_STATUS(STATUS_ID) ON DELETE CASCADE
);
