swagger: '2.0'
######################################################
# Prolog
######################################################
info:
  version: "1.0"
  title: "WSO2 Identity Server Rest API - Retryable Provisoning"
  description: |
    This document specifies a **RESTful API** for WSO2 **Identity Server** .

    It is written with [swagger 2](http://swagger.io/).

  contact:
    name: "WSO2"
    url: "http://wso2.com/products/identity-server/"
    email: "architecture@wso2.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

######################################################
# The fixed parts of the URLs of the API
######################################################

# The schemes supported by the API
schemes:
  - https

# The domain of the API.
# This is configured by the customer during deployment.
# The given host is just an example.
host: apis.is.com

# The base path of the API.
# Will be prefixed to all paths.
# if the tenant domain is carbon.super base path can be /api/identity/retryable/provisioning/v0.9 like this too.
basePath: /t/{tenant-domain}/api/identity/retryable/provisioning/v1.0

# The following media types can be passed as input in message bodies of the API.
# The actual media type must be specified in the Content-Type header field of the request.
# The default is json, i.e. the Content-Type header is not needed to
# be set, but supporting it serves extensibility.
consumes:
  - application/json

# The following media types may be passed as output in message bodies of the API.
# The media type(s) consumable by the request is specified in the Accept header field
# of the corresponding request.
# The actual media type returned will be specified in the Content-Type header field
# of the of the response.
# The default of the Accept header is json, i.e. there is not needed to
# set the value, but supporting it serves extensibility.
produces:
  - application/json
paths:
  # Endpoint uses to get provisioning information
  /provisioning-status:
    get:
      description: |
         This API is used to get provisioning status data from the backend.
      x-wso2-request: |
        curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json"
        "https://localhost:9443/api/identity/retryable/provisioning/v1.0/provisioning-status?
        status=SUCCESS&type=USER&name=test@wso2.com

      x-wso2-response: |
        "HTTP/1.1 200 OK"
      summary: |
        Get provisioning information.

      # This are the post parameters:
      parameters:
        -
          name: status
          in: query
          description:  The status of the provisioning
          required: false
          type: string
        -
          name: type
          in: query
          description: The provisioning entity type (user or group)
          required: false
          type: string

        -
          name: name
          in: query
          description:  The provisioned entity name.
          required: false
          type: string

      responses:
        200:
          description: Successful response
          schema:
            title: provisioningStatus
            type: array
            items:
              $ref: '#/definitions/ProvisioningStatus'

        400:
          description: Bad Request
          schema:
             $ref: '#/definitions/Error'

        500:
          description: Server Error
          schema:
             $ref: '#/definitions/Error'


    # Endpoint uses to reset user password
  /re-attempt:

    post:
      description: |
        This API will be used to reattept the set of selected failed provisionings.
      x-wso2-request: |
        curl -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d
        '{"provisioningIds":[1, 2, 4]}' "https://localhost:9443/api/identity/retryable/provisioning/v1.0/re-attempt"

      x-wso2-response: |
        "HTTP/1.1 200 OK"
      summary: |
        Retry provisioning.

      parameters:
        -
          name: provisioningIds
          in: body
          description:  List of provisioning status identifiers.
          required: true
          schema:
            $ref: '#/definitions/RetryProvisioningRequest'

      responses:
        202:
          description: Successful response

        400:
          description: Bad Request
          schema:
             $ref: '#/definitions/Error'

        500:
          description: Server Error
          schema:
             $ref: '#/definitions/Error'


  /delete-provisioning:
    post:
      description: |
        This API is used to delete the selected set of provisionings.
      x-wso2-request: |
        curl -k -v -X POST -H "Authorization: Basic YWRtaW46YWRtaW4=" -H "Content-Type: application/json" -d
         '{"provisioningIds":[1, 2, 4]}' "https://localhost:9443/api/identity/retryable/provisioning/v1.0/delete-provisioning"

      x-wso2-response: |
        "HTTP/1.1 202 Accepted"

      summary: |
        Delete Provisioning.

      # This are the post parameters:
      parameters:
        -
          name: provisioningIds
          in: body
          description:  The list of provisioning status ids to be deleted.
          required: true
          schema:
            $ref: '#/definitions/RetryProvisioningRequest'
      responses:
        202:
          description: Accepted

        400:
          description: Bad Request
          schema:
             $ref: '#/definitions/Error'

        500:
          description: Server Error
          schema:
             $ref: '#/definitions/Error'




definitions:
#-----------------------------------------------------
# The User  Object
#-----------------------------------------------------
  ProvisioningStatus:
    type: object
    properties:
      identifier:
        type: integer
      tenantId:
        type: integer
      status:
        type: string
      cause:
        type: string
      entity:
        type: string
      name:
        type: string
      operation:
        type: string
      idpName:
        type: string

#-----------------------------------------------------
# The Credential  object
#-----------------------------------------------------
  RetryProvisioningRequest:
    type: object
    properties:
      provisioningIds:
        type: array
        items:
          type: integer

#-----------------------------------------------------
# The Error Response  object
#-----------------------------------------------------
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
      description:
        type: string